### ISSUE TITLE
Linux Build Instructions

### ISSUE THREAD

**Issue by mcharleb** [eProsima/Fast-RTPS#107]
The Linux instructions don't describe the submodules, and the REQUIRED options to build FastRTPS.
These were the instructions I had to use on Linux to make a fully functional build:

sudo apt-get install gradle
git clone https://github.com/eProsima/Fast-RTPS
cd Fast-RTPS
git submodule update --init --recursive
mkdir build_tinyxml2
cd build_tinyxml2
cmake ../thirdparty/tinyxml2
make
sudo make install
cd ../
mkdir build
cd build
cmake DTHIRDPARTY=ON -DBUILD_JAVA=ON -DASIO_INCLUDE_DIR=`pwd`/../thirdparty/asio/asio/include -DTINYXML2_INCLUDE_DIR=`pwd`/../thirdparty/tinyxml2 -DTINYXML2_LIBRARY=/usr/local/lib/libtinyxml2.so ..
make
sudo make install

**Comment by mikaelarguedas** [comment]
I didn't have to do it for a while but I think that doing `git clone --recursive https://github.com/eProsima/Fast-RTPS` was all I needed to get the submodules. Then if you pass `-DTHIRDPARTY=ON` it will build the thirdparty libraries properly.

The way we do it on the ROS2 buildfarm is (note that we dont build the java bindings, only the  c++ code so it may not be exactly what you need)
```
sudo apt-get install libasio-dev libtinyxml2-dev
git clone https://github.com/eProsima/Fast-RTPS
cd Fast-RTPS
mkdir build
cd build
cmake ..
make
sudo make install
```

**Comment by mcharleb** [comment]
In order to use FastRPC with PX4 I need the java executables, and it wasn't documented anywhere how to do a full build.

**Comment by richiprosima** [comment]
FastRTPS uses three thirdparty libraries: FastCDR, Asio and Tinyxml2. You can compile FastRTPS having these libraries in your system as @mikaelarguedas said. But using ```-DTHIRDPARTY=ON```, FastRTPS will use the git submodules of these libraries located on ```thirdparty``` folder. This option will update the submodules, compile the FastCDR library and include the source code of asio and tinyxml2 in FastRTPS library compilation.

```
git clone https://github.com/eProsima/Fast-RTPS
cd Fast-RTPS
mkdir build
cd build
cmake -DTHIRDPARTY=ON ..
make
sudo make install
```

To generate ```fastrtpsgen```, the java executable, you need to use the option ```-DBUILD_JAVA=ON```. [Gradle](https://gradle.org/) has to be installed in the system because it's used for compiling ```fastrtpsgen```. Also git submodule ```thirdparty/idl``` has to be updated or you can use ```-DTHIRDPARTY=ON``` that updates it automatically.

```
git clone https://github.com/eProsima/Fast-RTPS
cd Fast-RTPS
mkdir build
cd build
cmake -DTHIRDPARTY=ON -DBUILD_JAVA=ON ..
make
sudo make install
```

We will try to improve our documentation.

**Comment by ufechner7** [comment]
As I wrote before, this is not sufficient because it doesn't install the .so files of the dependencies.

**Comment by JaimeMartin** [comment]
Hi Uwe,

We will check this issue in a clean machine.

**Comment by richiware** [comment]
Commit c53f9e9b800c8712b593e53e9102334434a145aa fixes the installation of Fast CDR when THIRDPARTY option is used.

**Comment by richiware** [comment]
I will close the issue. If there is any problem, you can reopen it. Thanks
