### ISSUE TITLE
Destructor for SenderResouce

### ISSUE THREAD

**Issue by glkhobragade** [eProsima/Fast-RTPS#173]
Once participant is created in the Fast-RTPS (i.e. Real time publisher subscriber, one of the DDS implementation) layer or any publisher is created, senderResource objects are created by the network factory inside RTPSParticipantImpl.cpp and keep the senderResource object with itself in a vector.

But if the publisher is removed, the corresponding senderResource object has to be deleted. But I am not able to find where/when the destructor of correspoding senderResource is called when corresponding Endpoint(reader/writer) is removed.

The vector inside RTPSParticipantImpl which has all senderResources is erased at the destruction of RTPSParticipantImpl only, which should not be the case. The entries should be removed on deletion of endpoint as well. Kindly clarify my understanding.

Code Link:
https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/rtps/participant/RTPSParticipantImpl.cpp#L394 https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/rtps/participant/RTPSParticipantImpl.cpp#L497

**Comment by richiware** [comment]
I will try to check it but not in short time.

**Comment by MiguelCompany** [comment]
Hi @glkhobragade 

Please bear in mind that sender resources can be shared. In fact, with the default configuration, only one sender resource will be created (when creating the participant). Later on, when creating/discovering endpoints it will be reused to send data to different locations.

That's why they are not removed until the destruction of the participant.
