### ISSUE TITLE
Incorrect gapList.base field in GAP submessage

### ISSUE THREAD

**Issue by guillaumeautran** [eProsima/Fast-RTPS#182]
According to the RTPS specs section 8.3.7.4.5, a recipient of a GAP message interprets the message such that:

- All sequence numbers in the range gapStart <= sequence_number <= gapList.base -1
- All the sequence numbers that appear explicitly listed in the gapList.

Given a GAP list of sequence numbers 8, 9, 10, 15, 16, 19, 20, 23, 27, 28 and the description above, the gap message should have the following values: gapStart==8, gapList.base==11 gapList.set[15, 16, 19, 20, 23, 27, 28]

Instead, the GAP message sent by the StatefulWriter has the following values: gapStart==8, gapList.base==8 gapList.set[9, 10, 15, 16, 19, 20, 23, 27, 28] causing the gap seqnum 8 to be missed by the receiver.

How to reproduce the issue:
1. Create a RTPS participant A
2. Create a RTPS participant B
3. Participant B publishes topic B_topic
4. Participant A subscribes to B_topic
5. Verify that data is received by participant A on B_topic
6. Shutdown cleanly participant B
7. Participant A removes subscription for B_topic
8. Start another instance of participant B which publishes B_topic
9. Participant A registers to B_topic
10. Verify that data is received by participant A on B_topic
11. Repeat steps 6-10 several times (typically 3 times is enough).
12. Observes that the new instance of participant B DOES NOT receives the data for A_topic. 

The reasons is that when the first instance of participant B shutsdown cleanly, some messages are removed from the RTPS Writer history in some of the internal fastrtps percistent topics. These gaps then segment the message sequence number causing the next participant to receive a GAP message causing it to skip sequence numbers. Because the GAP message is improperly configured, it causes the reader side to continuously request a missing message.

**Comment by wtsnyder** [comment]
We have occasionally seen issues similar to the symptoms you describe here where shutting down and restarting a participant resulted in a loss of data flow until restarting all participants.  Some of our issues were caused by #155 however we still have to restart all participants occasionally and haven't had time to really dig into the cause.

Does this issue affect participant discovery or just topic matching afterwards? We don't usually even see participant discovery (using onRTPSParticipantDiscovery callback) when we are having issues.

How can I confirm communications issues are caused by this GAP list issue when it is happening? Can you identify it from Wireshark traffic?

**Comment by guillaumeautran** [comment]
This impacts all reliable topics and as far as I know, all built-in topics are setup as reliable.
