### ISSUE TITLE
SubscriberHistory: pure virtual function call in destructor

### ISSUE THREAD

**Issue by liamstask** [eProsima/Fast-RTPS#30]
`~SubscriberHistory()` calls `TopicDataType::deleteData()`, which is a pure virtual function, in its destructor which gives the following output when cleaning up the application:

```
libc++abi.dylib: Pure virtual function called!
Abort trap: 6
```

It's not possible to make a virtual function call from a constructor or destructor, since the derived object hasn't been constructed or has already been destroyed. It then tries to call the base class implementation, which in the case of a pure virtual function doesn't exist, hence the error.

`~PublisherHistory()` looks like it does not do this, only because it has not yet been implemented. I haven't looked yet to see whether there are other instances of this.

**Comment by PabloMansanet** [comment]
Hello @liamstask 

I'm taking a look at this issue, and I'm slightly confused about why your tools are reporting a problem.

As you pointed out, we are calling a pure virtual from a destructor, however, that method is completely unrelated to the hierarchy of the class we are currently destroying.

`mp_subImpl->getType()->deleteData(mp_getKeyObject);`

If I understand correctly, getType will return a reference to a base class that is not currently being destroyed, so deleteData should follow the vtable normally. 

Is this a problem you can still reproduce? Otherwise, did it pertain to a particular branch?

Thanks!

**Comment by liamstask** [comment]
Hi @PabloMansanet - when the program exits, the order in which static/global destructors are called is not defined, in which case the class hierarchy is not relevant. This can prevent cleanup from happening on program shutdown.

**Comment by PabloMansanet** [comment]
@liamstask I'm afraid we're still scratching our heads at this one a little bit.

I understand that being an issue if the two objects were either static or scoped to different static objects, so their order of destruction would be undefined. However in this particular case, mp_subImpl's memory is owned by the ReaderHistory itself, so I can't imagine how you could get into a situation where mp_subImpl points to an object halfway through destruction.

What tools where you using when you saw this error reported? We haven't seen anything similar from any dynamic analysis tool.

**Comment by liamstask** [comment]
@PabloMansanet I believe the issue can occur because `mp_subImpl->getType()` returns a pointer to a `TopicDataType` which can be an object statically allocated by user code, which is not owned by FastRTPS. Now, both the `TopicDataType` pointed to by `mp_subImpl` and `SubscriberHistory` can be deallocated separately during shutdown, assuming both are statically allocated.

I was running locally on my OS X machine when this happened using the system standard clang-based toolchain.

**Comment by richiware** [comment]
We cannot still reproduce this issue after a long time. We close this issue.
