### ISSUE TITLE
Issue compiling Helloworld or examples with 32 bit [4626]

### ISSUE THREAD

**Issue by anandtp** [eProsima/Fast-RTPS#311]
Hi,

When I compile Helloworld example with 32 bit I get a runtime error, I suppose the libs not linking properly. Can I install 32 and 64 bit FastRTPS in the same location . Also for 32 bit I have to include fastrtps-1.6.lib for it to compile.

Regards,
Anand Pavaskar

**Comment by MiguelBarro** [comment]
Hi Anand,

I'm affraid you should provide some background context for us. What's your operating system? What's your compiler?

If you are using Windows, for example, the CMake installation would choose a different **Program Files** folder for 32 and 64 bits applications so no interference problem should arise. 

Please notice that CMake installation would not modify your OS environment variables so in order to run the example you should either:

- modify your system environment variables adding to the PATH variable the current dlls installation path. For example: **PATH=%PATH%;C:\Program Files\fastrtps\bin; C:\Program Files\fastcdr** in 64 bits. 

 You may rather prefer to modify your command prompt local variables to the same effect.

- copy fastcdr-1.0.dll and fastcdrd-1.0.dll to the HelloWorldExample.exe folder (or their debugging counterparts if not compiling in Release).

Hope it helps you!

**Comment by MiguelBarro** [comment]
Anand,

Our project lifecycle liveliness demands closing any inactive issue. Feel free to reopen it whenever you resume your work.
