### ISSUE TITLE
Why changed XMLProfileManager::loadDefaultXMLFile()'s return value to void [4924]

### ISSUE THREAD

**Issue by ahuizxc** [eProsima/Fast-RTPS#440]
I am very confused why changed this function's return value to void. Could you explain this change? thanks a lot :)

**Comment by LuisGP** [comment]
Hi, @ahuizxc

We changed the return value of `XMLProfileManager::loadDefaultXMLFile()` because it wasn't being used internally, and that function isn't supposed to be used by the user. Probably it will become non-public soon.
As user, you can call `XMLProfileManager::loadXMLFile(const std::string &filename)` which returns the loading result.

Hope this match your requirements.

**Comment by LuisGP** [comment]
As this was answered and no comments were received, we close the issue. Feel free to reopen if there is more clarification needed.
