### ISSUE TITLE
Fast-RTPS Fails to Compile on CentOS 7

### ISSUE THREAD

**Issue by jml1795** [eProsima/Fast-RTPS#494]
It looks like Fast-RTPS fails to compile on CentOS 7 due to a call to `std::put_time()` inside `src/cpp/log/Log.cpp`. This is because `put_time` wasn't implemented until Gcc 5.0 according to [this bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54354#c9). Unfortunately, CentOS 7 ships w/ Gcc 4.8.5 and upgrading may not be an option for all users.

I realize that `put_time` is part of C++-11, however, CentOS / RHEL are very popular OS's that may be worth supporting. Is there any chance there is an alternative implementation that you will accept to get around this issue?

This particular method appears to be pretty innocuous. I will take a look at an alternative implementation and open a PR. Thanks

**Comment by LuisGP** [comment]
Hi @jml1795 

We will discuss this issue internally once we release version 1.8.0. But our first thoughts are focused on don't step back in this kind of issues. 

Advance user shouldn't have problems upgrading their GCC, installing different versions if several are needed or installing different compilers like clang. I guess you understand that fixing an already fixed bug in a compiler due to users that don't want to upgrade isn't worth for us.

Additionally, this kind of users is always able to modify the code as you did to meet their requirements.

In any case, as I mentioned at the beginning, we will talk about it.

Thank you very much, best regards.

**Comment by jml1795** [comment]
@LuisGP Understood. I appreciate your consideration and the team's efforts w/ fast-rtps.

**Comment by tparys** [comment]
FYI, I have Fast-RTPS 1.7.2 compiling just fine on CentOS 7.

Two things I've noticed:

1. CMake 2 doesn't seem to be sufficient to generate the build environment. Need CMake 3 (don't remember if it was in the EPEL repo). Don't think this is adequately captured in the eProsima docs.

2. Yes, the default compiler is old. But you can easilly grab a new one via devtoolset.

https://www.softwarecollections.org/en/scls/rhscl/devtoolset-6/

Based on these two points, 1.7.2 built just fine for me.

**Comment by LuisGP** [comment]
We decided to not apply patches for this kind of issues. As mentioned, you can upgrade your GCC or install clang if you prefer.
