### ISSUE TITLE
[Question]Disabling serializeration/deserialization within FastRTPS [5689]

### ISSUE THREAD

**Issue by sriramster** [eProsima/Fast-RTPS#533]
Hi,

I'm using FastRTPS for one of the research projects. Trying to optimize the communication, is there a way to disable/by-pass serialization/deserialization of a message? Just curious if there is a easy way to do this.

Sriram

**Comment by AlvaroMolinillo** [comment]
Hi, 

At first, there is no way to do that. Data types must implement serialization/deserialization method to be transfered over RTPS protocol. But there is a workaround. You could implement serialization/deserialization methods overriding TopicDataType class with your desire data type in the way you prefer. You can just asign data to serializedPayload data instead of using a serialization class like Cdr as Helloworld example does. You should be careful with memory allocation. 

I hope this responds your question
