### ISSUE TITLE
Subscriber fails to receive message sometimes in different machines, however a discovery node will instantly make the subscriber work again. [6119]

### ISSUE THREAD

**Issue by breezZe** [eProsima/Fast-RTPS#581]
**Problems description**
I've met a problem publishing/subscribing messages in two different machines in the same sub net.

Subscriber on  PC A, Publisher on PC B. PC A and PC B are in the same sub net via WiFi.
Publisher keeps running and publish message in a process.
Subscriber occasionally read message in a process.  
I run subscriber on PC  A occasionally, but sometimes subscriber will not receive any message.

Ｂy the way, I wrote my own dds_monitor process to list all the message topic types and messages, which works as the **rostopic list** function. Whenever the subscriber can't receive message, just run this dds_monitor, the subscriber can receive message **AT ONCE**.

I'm wondering that which attribute could lead to problems I met above, and as I'm not so familiar with FastRTPS lower layer, it will be so nice of you to explain the **monitor solves the reception failure** issue.

Thanks a lot.
[cmdrmonitor.tar.gz](https://github.com/eProsima/Fast-RTPS/files/3343752/cmdrmonitor.tar.gz)

**Comment by richiware** [comment]
We are testing a solution to a similar case. Can you test using this [branch](https://github.com/eProsima/Fast-RTPS/tree/bugfix/5712)? Is this improve your communications over Wifi?

**Comment by breezZe** [comment]
@richiware I've built the branch and tried several times, seems problems not solved. Follows my initialization code for publisher and subscriber.
##### Publisher
```c++
        eprosima::fastrtps::PublisherAttributes Wparam;
        Wparam.topic.topicKind = eprosima::fastrtps::rtps::NO_KEY;
        Wparam.topic.topicDataType = m_type_.getName();
        Wparam.topic.topicName = topicname;
        Wparam.topic.historyQos.kind = eprosima::fastrtps::KEEP_LAST_HISTORY_QOS;
        Wparam.topic.historyQos.depth = history;
        Wparam.topic.resourceLimitsQos.max_samples = 200;
        Wparam.qos.m_reliability.kind = eprosima::fastrtps::RELIABLE_RELIABILITY_QOS;
        if (PublishMode == ASYNC_PUBLISH_MODE)
            Wparam.qos.m_publishMode.kind = eprosima::fastrtps::ASYNCHRONOUS_PUBLISH_MODE;
        mp_publisher_ = eprosima::fastrtps::Domain::createPublisher(mp_participant_,
                                                                    Wparam,
                                                                    (eprosima::fastrtps::PublisherListener *)&m_listener_);
```
##### Subscriber
```c++
m_listener_.callback_pointer_ = callback_ptr;
        Rparam.topic.topicKind = eprosima::fastrtps::rtps::NO_KEY;
        Rparam.topic.topicDataType = m_type_.getName();
        Rparam.topic.topicName = topicname;
        Rparam.topic.historyQos.kind = eprosima::fastrtps::KEEP_LAST_HISTORY_QOS;
        Rparam.topic.historyQos.depth = history;
        Rparam.topic.resourceLimitsQos.max_samples = 200;
        Rparam.qos.m_reliability.kind = eprosima::fastrtps::BEST_EFFORT_RELIABILITY_QOS;
        Rparam.qos.m_durability.kind = eprosima::fastrtps::VOLATILE_DURABILITY_QOS;
        mp_subscriber_ = eprosima::fastrtps::Domain::createSubscriber(mp_participant_,
                                                                      Rparam,
                                                                      (eprosima::fastrtps::SubscriberListener *)&m_listener_);
```

Is there any possibility that could lead to problems in my initial code?

**Comment by richiware** [comment]
I see the configuration is right. The only thing is your subscriber is configured in best-effort, without reliability. Can you provide us a Wireshark capture? Thanks.

**Comment by breezZe** [comment]
I captured the net data with Wireshark. 
The data package includes follow parts, 
1. Subscriber successfully receives message.
2. Kill subscriber process.
3. Reopen subscriber process. Now subscriber cannot received message.
4. Run [cmdrmonitor](https://github.com/breezZe/cmdrmonitor). 
5. Subscriber receives message again.
[subscriber_fail_rediscover.pcapng.tar.gz](https://github.com/eProsima/Fast-RTPS/files/3345226/subscriber_fail_rediscover.pcapng.tar.gz)

**Comment by MiguelBarro** [comment]
We have been trying to reproduce your issue for a while without any success.

### cmdrmonitor  review

First we build your monitor app. We found several issues in it that we have somehow workaround:

- The monitor actually creates a couple of Participants instead of one. The first participant does nothing but provide attributes for the second, that is a conceptual error. Besides both participants have the same name (its not a real error because participant name is disregarded for implementation issues).
        
- It's an odd custom listener because instead of enumerating the number of publishers, subscribers it actually the number of types and the associated topics for each type (for all publishers and subscribers).

In order to sweep off the screen as he wants he should:
+ use a mutex to avoid collection modification during printing (this can spoil its sweep strategy).
+ use a couple of counters because the number of lines to sweep may change.
+ sweep before writing not after.

We include here the sources changes that worked for us: [monitor.zip](https://github.com/eProsima/Fast-RTPS/files/3596125/monitor.zip)

### Testing scenario

Our testing scenario was a simple one based on ShapesDemo (https://github.com/eProsima/ShapesDemo) instead of using cumbersome ROS interfaces. We run several ShapesDemo applications on different PCs sharing the same Ethernet network and monitor them using cmdrmonitor without any issues.

We advice you to try it yourself and provide some Wireshark trace if detected any issue. Note that ShapesDemo would not admit your default 100 domain (max is 99), thus you should test cmdrmonitor  with a non-default domain value.

### Trace analysis

At first sight the trace traffic is odd. I would like to know which version of fastrtps library are you currently using.  Note that ordinary fastrtps traffic uses INFO_DST submessages to send DATA (usual INFO_DST, INFO_TS, DATA chain) but this trace uses INFO_TS, DATA, HEARTBEAT chains that doesn't match our current implementation. Note that reliable implies isolated INFO_DST, HEARTBEAT and INFO_DST, ACKNACK chains. This trace only uses INFO_DST for unicast metatraffic which is odd.

I exported the trace to a spreadsheet for further analysis: [BreezZe trace.xlsx](https://github.com/eProsima/Fast-RTPS/files/3596226/BreezZe.trace.xlsx)

- There are four monitors in two processes:
 010f2eb3e128000001000000    id3 (52s and 65s) 192.168.50.222
 010f2eb3e128000002000000    id4 (52s and 65s) 192.168.50.222           
 010fd97b0533000001000000    id8 (9s, 41s and 65s) 192.168.50.211
 010fd97b0533000002000000    id9 (9s, 41s and 65s) 192.168.50.211
- one unnamed participant that disappears in a controlled fashion 010f2eb37d28000001000000.
- There are two "Motion" in independent processes:
 010f2eb39128000001000000      id2  (24s, 30s, 41s, 52s, 64s) 192.168.50.222
 010febd3ff07000001000000      id10 (30s, 52s, 64s) 192.168.50.202
 - There are two "urgc_node" sharing process: 
 010fc9c32c19000001000000      id5  (9s, 15s, 55s) 192.168.50.211  
 010fc9c32c19000002000000      id6  (9s, 15s, 65s) 192.168.50.211
- Urg_test 010fc9c3e619000001000000     id7  (9s, 43s) 192.168.50.211
- robotcomm 010fef0d3a16000001000000    id11 (29s) 192.168.50.190
- cmd_msg 010fef0d710e000001000000      id12 (38s) 192.168.50.190
- anonymous participant that reports its dead at the beginning 010f2eb37d28000001000000.

In all cases lease duration announcement is the default one (40s). 

There are several discovery storms at 9, 15, 24, 29, 38, 52 and 64 seconds. 

Fast-RTPS participants answer any metatraffic from unknown participants on reception. But this behavior is not consistent with your trace. At 9s, 24s and 38s participant Motion (id10) should make an announcement but it doesn't. Possibly this can explain why your subscriber doesn't recibe till the monitor is created: 
+ Publisher doesn't reply to subscriber announcement, thus subscriber would have to wait for at least 40s in order to discover him.
+ Publisher announces in reply to monitor announcement. The subscriber receives this announcement and thus discovers the publisher.

We strongly advice you to test our ShapesDemo scenario and send us some traces if the problem persist. Please document which version of the library you are using to get more insight from the analysis of the trace.

Regards,
