### ISSUE TITLE
how to send message to specific subscriber in the same domain on the same topic [6118]

### ISSUE THREAD

**Issue by gaoyadianta** [eProsima/Fast-RTPS#601]
i have a problem like this:
i created a topic called "Hello", and the topic has 1 publisher and 10 subscriber.
now i just want to send  a Hello message to subscriberNo.1 only(subscriber 2-10 can not receive)
how can i did this? anyone can help?

**Comment by laura-eprosima** [comment]
Hi @gaoyadianta,
This problem can be solved using partitions. This feature allows you to separate the messages send for instance to subscriber 1.

To use it, you need to specify in the subscriber attributes the name of the partition or partitions where the subscriber will be and therefore whose message will receive. 

`Rparam_sub1.qos.m_partition.push_back("Subs1_partition");`

Apart from that, you also need to configure where is the publisher going to send the messages.

`Wparam.qos.m_partition.push_back("Subs1_partition");`

So that, every time the publisher sends a message it will be received only by those subscribers in the partition.

I hope this helps you. I'm closing the issue but if you need more information feel free to reopen it.
