### ISSUE TITLE
Support for DDS-XTypes 1.2

### ISSUE THREAD

**Issue by rnareddy646** [eProsima/Fast-RTPS#903]
Hello,

I would like to ask if the Fast RTPS implementation supports any of the
Extensible and Dynamic Topic Types for DDS as seen in the
https://www.omg.org/spec/DDS-XTypes/1.2

Please help us on this , we are trying to check interoperability test between different vendors to see if this supports.
Thanks 
Sudharsan

**Comment by rburchell** [comment]
[The documentation](https://fast-rtps.docs.eprosima.com/en/latest/dynamictypes.html) might be worth looking at.

**Comment by rnareddy646** [comment]
Thank you for pointing out to the documentation link, Will go through that.

**Comment by richiware** [comment]
@rnareddy646 Does the documentation help you? If it was helpful, could you close the issue? Thanks

**Comment by i-and** [comment]
Please specify the implementation status of the following parts of the DDS-XTypes standard:

1. IDL/XML parser and Fast-RTPS (de)serializer support for data type evolution with @extensibility=mutable| append|final, id, optional, mustUnderstand, tryConstruct;
2. discovery-Time Data Typing (the dynamic features of DDS-XTypes depend on the ability of components to discover the data types used by their peers);
3.  introspecting existing types by user;
4. Type Consistency Enforcement at Discovery-Time.

**Comment by richiware** [comment]
The current status in `master` is:

> 1. IDL/XML parser and Fast-RTPS (de)serializer support for data type evolution with @extensibility=mutable| append|final, id, optional, mustUnderstand, tryConstruct;

Our [idl generator](https://github.com/eProsima/Fast-RTPS-Gen) supports those annotations. But our [serialization library](https://github.com/eProsima/Fast-CDR) doesn't still support XCDR standard, needed to use those annotations at serialization.

> 2. discovery-Time Data Typing (the dynamic features of DDS-XTypes depend on the ability of components to discover the data types used by their peers);

You have documentation about this [here](https://github.com/eProsima/Fast-RTPS-docs/blob/master/docs/dynamictypes.rst#discovery-time-data-typing). The feature is in `master` but not released yet in an official release.

> 3. introspecting existing types by user;

The user is able to introspect existing dynamic types. Maybe this [example](https://github.com/eProsima/Fast-RTPS/tree/master/examples/C%2B%2B/DDS/DynamicHelloWorldExample) and this [one](https://github.com/eProsima/Fast-RTPS/tree/master/examples/C%2B%2B/DDS/TypeLookupService) could help you.

> 4. Type Consistency Enforcement at Discovery-Time.

At discovery level, Fast-RTPS is prepared, but Fast-CDR is still not supporting XCDR.

Support all DDS-XTypes 1.2 is in the eProsima's roadmap.

**Comment by rnareddy646** [comment]
Thank you for your support on this

**Comment by richiware** [comment]
You're welcome. I close the issue.

**Comment by vireshshirol** [comment]
Hi ,
I was trying to check the sample code workign for inherited struct types in the IDL.
Though the subscriber seems to receive the data from other applications, the publisher crashes in CDR serialize(int32) with NoMemoryException.

I was wondering if it was related to the incomplete support for XCDR in serialization library.
Could you please confirm if the sample generated for the following IDL is due to this issue?

struct Msg {
    @Key long userID;
    //@ID 0
    string message;    //@ID 1

};
//@Extensibility EXTENSIBLE_EXTENSIBILITY

struct MsgExtended : Msg {
    long dummy;    //@ID 2
};
//@Extensibility EXTENSIBLE_EXTENSIBILITY

[HelloWorld_IDL.txt](https://github.com/eProsima/Fast-RTPS/files/3960647/HelloWorld_IDL.txt)

I made further changes in the test code (and some debug logs in Cdr.cpp too)to check if things would work but without any luck.
As the sample code itself crashes ,I am atttaching only the IDL .
Please let me know if any additional info is required.
The installation was from master. (i.e. compiled from source)

Thank you,
Viresh
